### ISSUE TITLE
Can't connect via some IPs/URLs

### ISSUE THREAD

**Issue by drexelguy264** [jaeone94/stable-browser#2]
I have a server running in my house that I can connect to via local name and local IP address (eg http://NAME:7860 or 192.168.x.x:7860) but this only works when home. I have NordVPN Meshnet setup which gives it a unique URL and IP address and allows me to connect to it from anywhere. It's a similar format - http://nordvpndns.nord:7860 or 100.x.x.x. 

NordVPN Meshnet works in Safari and Chrome. I can ping the endpoint in the Fing app. That said, Stable Browser only lets me use a local IP address [when I'm home] and not use the server over VPN. 

The only other test I can think of is whether I can connect to an internet facing server.

**Comment by jaeone94** [comment]
Hi, thank you for sharing your issue. I have identified the same issue and made some modifications to the code. Is this the issue you have identified in the version deployed in the app store, and if so, could I ask you to join the public beta via the following URL to see if I have fixed it and if the issue persists in the latest test version ? 

https://testflight.apple.com/join/5R8Z9JyS

Thank you again for bringing this issue to our attention.

**Comment by drexelguy264** [comment]
The issue is with the version in the App Store. I'm also having the same
issue in the latest version in the public beta that you linked.

**Comment by jaeone94** [comment]
Can you try adding "--share" to your COMMANDLINE ARGS and connecting to a public address that starts with https:// and ends with gradio.app? 

If you can connect, we'll know what the issue is. 
We'll take action within 48 hours and update the public beta with a new version.
